import type { NextPage } from 'next'
import Head from 'next/head'
import Header from 'components/Header'
import { useModal } from 'hooks/useModal'
import Modal from 'components/Modal'

const Home: NextPage = () => {
  const { showModal } = useModal()

  return (
    <div className='h-screen bg-gradient-to-tr from-white to-purple-50'>
      <Head>
        <title>InfoWebs | Guarda tus marcadores de Chrome de una mejor manera!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className='max-w-screen-lg mx-auto pt-40 text-center'>
          <h3 className='text-6xl font-bold bg-gradient-to-r from-purple-600 to-purple-900 text-transparent bg-clip-text'>Optimiza tus marcadores!</h3>
          <p className='mt-4 text-slate-500'>Proyecto para guardar y manejar todos los marcadores que tenemos en nuestro navegador</p>
          <div className='my-20 max-w-screen-sm mx-auto rounded-lg bg-slate-100 p-2 flex gap-2'>
            <button className='px-2 py-1 rounded-lg bg-slate-200 text-slate-600 hover:bg-slate-300 transition active:brightness-95'>
              React
            </button>
            <button className='px-2 py-1 rounded-lg bg-slate-200 text-slate-600 hover:bg-slate-300 transition active:brightness-95'>
              JavaScript
            </button>
            <button className='px-2 py-1 rounded-lg bg-slate-200 text-slate-600 hover:bg-slate-300 transition active:brightness-95'>
              CMD
            </button>
            <button className='px-2 py-1 rounded-lg bg-slate-200 text-slate-600 hover:bg-slate-300 transition active:brightness-95'>
              Node
            </button>
            <button className='px-2 py-1 rounded-lg bg-slate-200 text-slate-600 hover:bg-slate-300 transition active:brightness-95'>
              Otros marcadores...
            </button>
          </div>
        </div>
        {
          showModal && <Modal />
        }
      </main>
    </div>
  )
}

export default Home
